name: Daily Awesomeness Reminder

on:
  schedule:
    # Runs at 7:30 AM Eastern Time (12:30 PM UTC during EST, 11:30 AM UTC during EDT)
    - cron: '30 12 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    
    - name: Run reminder script
      env:
        LLM_PROVIDER: anthropic
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        ANTHROPIC_MODEL: claude-3-haiku-20240307
        # Add email/SMS credentials if needed
      run: |
        pipenv run python main.py
